# Artemis configuration
spring:
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: max
    password: tihon

jms:
  queue: test-queue

# Camunda configuration
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
      lock-duration: 10000
      subscriptions:
        scoreProvider:
          variable-names: []
          process-definition-key: loan_process
        loanGranter:
          variable-names: customerId, creditScore
          process-definition-key: loan_process

logging:
  level:
    org.camunda.bpm.client: DEBUG

# Spring configuration    
server:
  port: 5050
